go_import_path: github.com/bubblesly/go-jsonnet
language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - goveralls -service=travis-ci
  - ./tests.sh --skip-go-test
